package com.threeti.danone.android.db.dao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.threeti.danone.common.bean.Stool;
import com.threeti.danone.common.bean.Feed;
import com.threeti.danone.common.bean.Crying;
import com.threeti.danone.common.bean.Dm;
import com.threeti.danone.common.bean.Notification;
import com.threeti.danone.common.bean.TimeSpent;
import com.threeti.danone.common.bean.DiaryReg;

import com.threeti.danone.android.db.dao.StoolDao;
import com.threeti.danone.android.db.dao.FeedDao;
import com.threeti.danone.android.db.dao.CryingDao;
import com.threeti.danone.android.db.dao.DmDao;
import com.threeti.danone.android.db.dao.NotificationDao;
import com.threeti.danone.android.db.dao.TimeSpentDao;
import com.threeti.danone.android.db.dao.DiaryRegDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stoolDaoConfig;
    private final DaoConfig feedDaoConfig;
    private final DaoConfig cryingDaoConfig;
    private final DaoConfig dmDaoConfig;
    private final DaoConfig notificationDaoConfig;
    private final DaoConfig timeSpentDaoConfig;
    private final DaoConfig diaryRegDaoConfig;

    private final StoolDao stoolDao;
    private final FeedDao feedDao;
    private final CryingDao cryingDao;
    private final DmDao dmDao;
    private final NotificationDao notificationDao;
    private final TimeSpentDao timeSpentDao;
    private final DiaryRegDao diaryRegDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stoolDaoConfig = daoConfigMap.get(StoolDao.class).clone();
        stoolDaoConfig.initIdentityScope(type);

        feedDaoConfig = daoConfigMap.get(FeedDao.class).clone();
        feedDaoConfig.initIdentityScope(type);

        cryingDaoConfig = daoConfigMap.get(CryingDao.class).clone();
        cryingDaoConfig.initIdentityScope(type);

        dmDaoConfig = daoConfigMap.get(DmDao.class).clone();
        dmDaoConfig.initIdentityScope(type);

        notificationDaoConfig = daoConfigMap.get(NotificationDao.class).clone();
        notificationDaoConfig.initIdentityScope(type);

        timeSpentDaoConfig = daoConfigMap.get(TimeSpentDao.class).clone();
        timeSpentDaoConfig.initIdentityScope(type);

        diaryRegDaoConfig = daoConfigMap.get(DiaryRegDao.class).clone();
        diaryRegDaoConfig.initIdentityScope(type);

        stoolDao = new StoolDao(stoolDaoConfig, this);
        feedDao = new FeedDao(feedDaoConfig, this);
        cryingDao = new CryingDao(cryingDaoConfig, this);
        dmDao = new DmDao(dmDaoConfig, this);
        notificationDao = new NotificationDao(notificationDaoConfig, this);
        timeSpentDao = new TimeSpentDao(timeSpentDaoConfig, this);
        diaryRegDao = new DiaryRegDao(diaryRegDaoConfig, this);

        registerDao(Stool.class, stoolDao);
        registerDao(Feed.class, feedDao);
        registerDao(Crying.class, cryingDao);
        registerDao(Dm.class, dmDao);
        registerDao(Notification.class, notificationDao);
        registerDao(TimeSpent.class, timeSpentDao);
        registerDao(DiaryReg.class, diaryRegDao);
    }
    
    public void clear() {
        stoolDaoConfig.getIdentityScope().clear();
        feedDaoConfig.getIdentityScope().clear();
        cryingDaoConfig.getIdentityScope().clear();
        dmDaoConfig.getIdentityScope().clear();
        notificationDaoConfig.getIdentityScope().clear();
        timeSpentDaoConfig.getIdentityScope().clear();
        diaryRegDaoConfig.getIdentityScope().clear();
    }

    public StoolDao getStoolDao() {
        return stoolDao;
    }

    public FeedDao getFeedDao() {
        return feedDao;
    }

    public CryingDao getCryingDao() {
        return cryingDao;
    }

    public DmDao getDmDao() {
        return dmDao;
    }

    public NotificationDao getNotificationDao() {
        return notificationDao;
    }

    public TimeSpentDao getTimeSpentDao() {
        return timeSpentDao;
    }

    public DiaryRegDao getDiaryRegDao() {
        return diaryRegDao;
    }

}
