package com.threeti.danone.android.db.dao;

import android.database.Cursor;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.database.DatabaseStatement;

import com.threeti.danone.common.bean.Feed;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "feed".
*/
public class FeedDao extends AbstractDao<Feed, String> {

    public static final String TABLENAME = "feed";

    /**
     * Properties of entity Feed.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property AppId = new Property(0, String.class, "appId", true, "APP_ID");
        public final static Property ServerId = new Property(1, String.class, "serverId", false, "server_Id");
        public final static Property ModifyReason = new Property(2, String.class, "modifyReason", false, "modify_reason");
        public final static Property DeleteReason = new Property(3, String.class, "deleteReason", false, "delete_reason");
        public final static Property InfantId = new Property(4, String.class, "infantId", false, "infant_id");
        public final static Property Status = new Property(5, Integer.class, "status", false, "STATUS");
        public final static Property Ddat = new Property(6, java.util.Date.class, "ddat", false, "DDAT");
        public final static Property StudyNumber = new Property(7, Integer.class, "studyNumber", false, "study_number");
        public final static Property FormulaNumber = new Property(8, Integer.class, "formulaNumber", false, "formula_number");
        public final static Property BeverNumber = new Property(9, Integer.class, "beverNumber", false, "bever_number");
        public final static Property CompNumber = new Property(10, Integer.class, "compNumber", false, "comp_number");
        public final static Property BreastNumber = new Property(11, Integer.class, "breastNumber", false, "breast_number");
    };


    public FeedDao(DaoConfig config) {
        super(config);
    }
    
    public FeedDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"feed\" (" + //
                "\"APP_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: appId
                "\"server_Id\" TEXT," + // 1: serverId
                "\"modify_reason\" TEXT," + // 2: modifyReason
                "\"delete_reason\" TEXT," + // 3: deleteReason
                "\"infant_id\" TEXT," + // 4: infantId
                "\"STATUS\" INTEGER," + // 5: status
                "\"DDAT\" INTEGER NOT NULL ," + // 6: ddat
                "\"study_number\" INTEGER," + // 7: studyNumber
                "\"formula_number\" INTEGER," + // 8: formulaNumber
                "\"bever_number\" INTEGER," + // 9: beverNumber
                "\"comp_number\" INTEGER," + // 10: compNumber
                "\"breast_number\" INTEGER);"); // 11: breastNumber
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"feed\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(DatabaseStatement stmt, Feed entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getAppId());
 
        String serverId = entity.getServerId();
        if (serverId != null) {
            stmt.bindString(2, serverId);
        }
 
        String modifyReason = entity.getModifyReason();
        if (modifyReason != null) {
            stmt.bindString(3, modifyReason);
        }
 
        String deleteReason = entity.getDeleteReason();
        if (deleteReason != null) {
            stmt.bindString(4, deleteReason);
        }
 
        String infantId = entity.getInfantId();
        if (infantId != null) {
            stmt.bindString(5, infantId);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(6, status);
        }
        stmt.bindLong(7, entity.getDdat().getTime());
 
        Integer studyNumber = entity.getStudyNumber();
        if (studyNumber != null) {
            stmt.bindLong(8, studyNumber);
        }
 
        Integer formulaNumber = entity.getFormulaNumber();
        if (formulaNumber != null) {
            stmt.bindLong(9, formulaNumber);
        }
 
        Integer beverNumber = entity.getBeverNumber();
        if (beverNumber != null) {
            stmt.bindLong(10, beverNumber);
        }
 
        Integer compNumber = entity.getCompNumber();
        if (compNumber != null) {
            stmt.bindLong(11, compNumber);
        }
 
        Integer breastNumber = entity.getBreastNumber();
        if (breastNumber != null) {
            stmt.bindLong(12, breastNumber);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Feed readEntity(Cursor cursor, int offset) {
        Feed entity = new Feed( //
            cursor.getString(offset + 0), // appId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // serverId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // modifyReason
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // deleteReason
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // infantId
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // status
            new java.util.Date(cursor.getLong(offset + 6)), // ddat
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // studyNumber
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // formulaNumber
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // beverNumber
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // compNumber
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11) // breastNumber
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Feed entity, int offset) {
        entity.setAppId(cursor.getString(offset + 0));
        entity.setServerId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setModifyReason(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeleteReason(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setInfantId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStatus(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDdat(new java.util.Date(cursor.getLong(offset + 6)));
        entity.setStudyNumber(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setFormulaNumber(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setBeverNumber(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setCompNumber(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setBreastNumber(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Feed entity, long rowId) {
        return entity.getAppId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Feed entity) {
        if(entity != null) {
            return entity.getAppId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
