package com.danone.comfit.common.model;

import com.danone.comfit.common.bean.Diary;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "stool".
 */
public class Stool extends Diary  {

	//stool type
	public static final int STOOL_WATERY = 1   ;  
	
	public static final int STOOL_SOFT   = 2   ;  
	
	public static final int STOOL_FORMED = 3   ;  
	
	public static final int STOOL_HARD   = 4   ;  
	
	public static final String STOOL_YES = "Y" ;
	
	public static final String STOOL_NO  = "N" ;
	
    private String stoolyn;
    
    private Integer type;
    
    private Integer amount;  // now not used
    

    public Stool() {
    }

    public Stool(String appId, String serverId, String modifyReason, String deleteReason, String infantId, java.util.Date ddat, Integer status, String stoolyn, Integer type, Integer amount) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.ddat = ddat;
        this.status = status;
        this.stoolyn = stoolyn;
        this.type = type;
        this.amount = amount;
    }

    public String getStoolyn() {
        return stoolyn;
    }

    public void setStoolyn(String stoolyn) {
        this.stoolyn = stoolyn;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

}
