package com.danone.comfit.common.bean;

import com.danone.comfit.common.util.TwoMin;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "Crying".
 */
public class Crying  extends Diary implements TwoMin{

	//1: fussing, 2: crying
    private String crytype;
    //morning,afternoon,evening,night
    private String timeOfDay;
    //N:no inconsolable,Y:Yes inconsolable
    private String cryinyn;
    //min unit(以分为单位 9：30 = 9* 60 + 30)
    private long crysttim;
    //min unit(以分为单位 9：30 = 9* 60 + 30)
    private long cryentim;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Crying() {
    }

    public Crying(String appId, String serverId, String modifyReason, String deleteReason, String infantId, java.util.Date ddat, Integer status, String crytype, String timeOfDay, String cryinyn, long crysttim, long cryentim) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.ddat = ddat;
        this.status = status;
        this.crytype = crytype;
        this.timeOfDay = timeOfDay;
        this.cryinyn = cryinyn;
        this.crysttim = crysttim;
        this.cryentim = cryentim;
    }

    public String getCrytype() {
        return crytype;
    }

    public void setCrytype(String crytype) {
        this.crytype = crytype;
    }

    public String getTimeOfDay() {
        return timeOfDay;
    }

    public void setTimeOfDay(String timeOfDay) {
        this.timeOfDay = timeOfDay;
    }

    public String getCryinyn() {
        return cryinyn;
    }

    public void setCryinyn(String cryinyn) {
        this.cryinyn = cryinyn;
    }

    public long getCrysttim() {
        return crysttim;
    }

    public void setCrysttim(long crysttim) {
        this.crysttim = crysttim;
    }

    public long getCryentim() {
        return cryentim;
    }

    public void setCryentim(long cryentim) {
        this.cryentim = cryentim;
    }

    // KEEP METHODS - put your custom methods here
    @Override
	public boolean isJudgeIntersect(TwoMin otherTwoMin) {
		if( getMax() <= otherTwoMin.getMin()){
			return false ;
		}
		if(otherTwoMin.getMax() <= getMin()){
			return false ;
		}
		return true ;
	}

	@Override
	public long getMax() {
		return cryentim;
	}

	@Override
	public long getMin() {
		return crysttim;
	}
    // KEEP METHODS END

}
