package com.danone.comfit.common.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "timespent".
 */
public class TimeSpent   extends Diary{

    private String diaryRegId;
    //1: app,2: feeding,3: stool,4: crying
    private String type;
    // second unit(以秒为单位 )
    private Integer time;

    // KEEP FIELDS - put your custom fields here
    public static final String APP_TYPE     = "1" ;
    public static final String FEEDINF_TYPE = "2" ;
    public static final String STOOL_TYPE   = "3" ;
    public static final String CRYING_TYPE  = "4" ;
    // KEEP FIELDS END

    public TimeSpent() {
    }

   
    public TimeSpent(String appId, String serverId, String modifyReason, String deleteReason, String infantId, String diaryRegId, Integer status, java.util.Date ddat, String type, Integer time) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.diaryRegId = diaryRegId;
        this.status = status;
        this.ddat = ddat;
        this.type = type;
        this.time = time;
    }


    public String getDiaryRegId() {
        return diaryRegId;
    }

    public void setDiaryRegId(String diaryRegId) {
        this.diaryRegId = diaryRegId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getTime() {
        return time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here
    public boolean isModuleTimeSpent(){
    	if(APP_TYPE.equals(type)){
    		return false ;
    	}
    	return true ;
    }
    // KEEP METHODS END

    
}
