package com.threeti.danone.common.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Crying".
 */
public class Crying {

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String app_id;
    private String infant_id;
    /** Not-null value. */
    private String crytype;
    private String modify_reason;
    private String delete_reason;
    private String time_of_day;
    private String cryinyn;
    private long ddat;
    private long crysttim;
    private long cryentim;
    private Integer delete_status;

    public Crying() {
    }

    public Crying(String id, String app_id, String infant_id, String crytype, String modify_reason, String delete_reason, String time_of_day, String cryinyn, long ddat, long crysttim, long cryentim, Integer delete_status) {
        this.id = id;
        this.app_id = app_id;
        this.infant_id = infant_id;
        this.crytype = crytype;
        this.modify_reason = modify_reason;
        this.delete_reason = delete_reason;
        this.time_of_day = time_of_day;
        this.cryinyn = cryinyn;
        this.ddat = ddat;
        this.crysttim = crysttim;
        this.cryentim = cryentim;
        this.delete_status = delete_status;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getApp_id() {
        return app_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApp_id(String app_id) {
        this.app_id = app_id;
    }

    public String getInfant_id() {
        return infant_id;
    }

    public void setInfant_id(String infant_id) {
        this.infant_id = infant_id;
    }

    /** Not-null value. */
    public String getCrytype() {
        return crytype;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCrytype(String crytype) {
        this.crytype = crytype;
    }

    public String getModify_reason() {
        return modify_reason;
    }

    public void setModify_reason(String modify_reason) {
        this.modify_reason = modify_reason;
    }

    public String getDelete_reason() {
        return delete_reason;
    }

    public void setDelete_reason(String delete_reason) {
        this.delete_reason = delete_reason;
    }

    public String getTime_of_day() {
        return time_of_day;
    }

    public void setTime_of_day(String time_of_day) {
        this.time_of_day = time_of_day;
    }

    public String getCryinyn() {
        return cryinyn;
    }

    public void setCryinyn(String cryinyn) {
        this.cryinyn = cryinyn;
    }

    public long getDdat() {
        return ddat;
    }

    public void setDdat(long ddat) {
        this.ddat = ddat;
    }

    public long getCrysttim() {
        return crysttim;
    }

    public void setCrysttim(long crysttim) {
        this.crysttim = crysttim;
    }

    public long getCryentim() {
        return cryentim;
    }

    public void setCryentim(long cryentim) {
        this.cryentim = cryentim;
    }

    public Integer getDelete_status() {
        return delete_status;
    }

    public void setDelete_status(Integer delete_status) {
        this.delete_status = delete_status;
    }

}
