package com.threeti.danone.common.bean;

import com.threeti.danone.common.model.Diary;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "Crying".
 */
public class Crying extends Diary  {
	
    private String crytype;
    private String timeOfDay;
    private String cryinyn;
    private long crysttim;
    private long cryentim;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Crying() {
    }

    public Crying(String appId) {
        this.appId = appId;
    }

    public Crying(String appId, String serverId, String modifyReason, String deleteReason, String infantId, java.util.Date ddat, Integer status, String crytype, String timeOfDay, String cryinyn, long crysttim, long cryentim) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.ddat = ddat;
        this.status = status;
        this.crytype = crytype;
        this.timeOfDay = timeOfDay;
        this.cryinyn = cryinyn;
        this.crysttim = crysttim;
        this.cryentim = cryentim;
    }


    public String getCrytype() {
        return crytype;
    }

    public void setCrytype(String crytype) {
        this.crytype = crytype;
    }

    public String getTimeOfDay() {
        return timeOfDay;
    }

    public void setTimeOfDay(String timeOfDay) {
        this.timeOfDay = timeOfDay;
    }

    public String getCryinyn() {
        return cryinyn;
    }

    public void setCryinyn(String cryinyn) {
        this.cryinyn = cryinyn;
    }

    public long getCrysttim() {
        return crysttim;
    }

    public void setCrysttim(long crysttim) {
        this.crysttim = crysttim;
    }

    public long getCryentim() {
        return cryentim;
    }

    public void setCryentim(long cryentim) {
        this.cryentim = cryentim;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
