package com.threeti.danone.common.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "diaryreg".
 */
public class DiaryReg  extends Diary {

    

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DiaryReg() {
    }

    public DiaryReg(String appId) {
        this.appId = appId;
    }

    public DiaryReg(String appId, String serverId, String modifyReason, String deleteReason, String infantId, Integer status, java.util.Date ddat) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.status = status;
        this.ddat = ddat;
    }

   
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
