package com.threeti.danone.common.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "feed".
 */
public class Feed   extends Diary{

    private String  timeOfDay;
    private Integer feedScoop;
    private Integer feedPrep;
    private Integer feedLeft;
    private Integer feedcon;

    // KEEP FIELDS - put your custom fields here
    //Night = 12am – 6am
    public static final String NIGHT     = "night"     ;
    //Morning = 6am – 12pm
    public static final String MORNING   = "morning"   ;
    //Afternoon = 12pm – 6pm
    public static final String AFTERNOON = "afternoon" ;
    //Evening = 6pm – 12am
    public static final String EVENING   = "evening"   ;
    // KEEP FIELDS END

    public Feed() {
    }

   
    public Feed(String appId, String serverId, String modifyReason, String deleteReason, String infantId, Integer status, java.util.Date ddat, String timeOfDay, Integer feedScoop, Integer feedPrep, Integer feedLeft, Integer feedcon) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.status = status;
        this.ddat = ddat;
        this.timeOfDay = timeOfDay;
        this.feedScoop = feedScoop;
        this.feedPrep = feedPrep;
        this.feedLeft = feedLeft;
        this.feedcon = feedcon;
    }
    
    public String getTimeOfDay() {
        return timeOfDay;
    }

    public void setTimeOfDay(String timeOfDay) {
        this.timeOfDay = timeOfDay;
    }

    public Integer getFeedScoop() {
        return feedScoop;
    }

    public void setFeedScoop(Integer feedScoop) {
        this.feedScoop = feedScoop;
    }

    public Integer getFeedPrep() {
        return feedPrep;
    }

    public void setFeedPrep(Integer feedPrep) {
        this.feedPrep = feedPrep;
    }

    public Integer getFeedLeft() {
        return feedLeft;
    }

    public void setFeedLeft(Integer feedLeft) {
        this.feedLeft = feedLeft;
    }

    public Integer getFeedcon() {
        return feedcon;
    }

    public void setFeedcon(Integer feedcon) {
        this.feedcon = feedcon;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
