package com.threeti.danone.common.bean;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "feed".
 */
public class Feed extends Diary  {

    /** Not-null value. */
    private String appId;
    private String serverId;
    private String modifyReason;
    private String deleteReason;
    private String infantId;
    private Integer status;
    /** Not-null value. */
    private java.util.Date ddat;
    private Integer studyNumber;
    private Integer formulaNumber;
    private Integer beverNumber;
    private Integer compNumber;
    private Integer breastNumber;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Feed() {
    }

    public Feed(String appId) {
        this.appId = appId;
    }

    public Feed(String appId, String serverId, String modifyReason, String deleteReason, String infantId, Integer status, java.util.Date ddat, Integer studyNumber, Integer formulaNumber, Integer beverNumber, Integer compNumber, Integer breastNumber) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.status = status;
        this.ddat = ddat;
        this.studyNumber = studyNumber;
        this.formulaNumber = formulaNumber;
        this.beverNumber = beverNumber;
        this.compNumber = compNumber;
        this.breastNumber = breastNumber;
    }

    /** Not-null value. */
    public String getAppId() {
        return appId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getServerId() {
        return serverId;
    }

    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    public String getModifyReason() {
        return modifyReason;
    }

    public void setModifyReason(String modifyReason) {
        this.modifyReason = modifyReason;
    }

    public String getDeleteReason() {
        return deleteReason;
    }

    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason;
    }

    public String getInfantId() {
        return infantId;
    }

    public void setInfantId(String infantId) {
        this.infantId = infantId;
    }


    /** Not-null value. */
    public java.util.Date getDdat() {
        return ddat;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDdat(java.util.Date ddat) {
        this.ddat = ddat;
    }

    public Integer getStudyNumber() {
        return studyNumber;
    }

    public void setStudyNumber(Integer studyNumber) {
        this.studyNumber = studyNumber;
    }

    public Integer getFormulaNumber() {
        return formulaNumber;
    }

    public void setFormulaNumber(Integer formulaNumber) {
        this.formulaNumber = formulaNumber;
    }

    public Integer getBeverNumber() {
        return beverNumber;
    }

    public void setBeverNumber(Integer beverNumber) {
        this.beverNumber = beverNumber;
    }

    public Integer getCompNumber() {
        return compNumber;
    }

    public void setCompNumber(Integer compNumber) {
        this.compNumber = compNumber;
    }

    public Integer getBreastNumber() {
        return breastNumber;
    }

    public void setBreastNumber(Integer breastNumber) {
        this.breastNumber = breastNumber;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
