package com.threeti.danone.common.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "spitting_up".
 */
public class Spitting_up {

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String app_id;
    private String modify_reason;
    private String delete_reason;
    private String infant_id;
    private long ddat;
    private Integer type;
    private Integer amount;
    private Integer delete_status;

    public Spitting_up() {
    }

    public Spitting_up(String id, String app_id, String modify_reason, String delete_reason, String infant_id, long ddat, Integer type, Integer amount, Integer delete_status) {
        this.id = id;
        this.app_id = app_id;
        this.modify_reason = modify_reason;
        this.delete_reason = delete_reason;
        this.infant_id = infant_id;
        this.ddat = ddat;
        this.type = type;
        this.amount = amount;
        this.delete_status = delete_status;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getApp_id() {
        return app_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApp_id(String app_id) {
        this.app_id = app_id;
    }

    public String getModify_reason() {
        return modify_reason;
    }

    public void setModify_reason(String modify_reason) {
        this.modify_reason = modify_reason;
    }

    public String getDelete_reason() {
        return delete_reason;
    }

    public void setDelete_reason(String delete_reason) {
        this.delete_reason = delete_reason;
    }

    public String getInfant_id() {
        return infant_id;
    }

    public void setInfant_id(String infant_id) {
        this.infant_id = infant_id;
    }

    public long getDdat() {
        return ddat;
    }

    public void setDdat(long ddat) {
        this.ddat = ddat;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Integer getDelete_status() {
        return delete_status;
    }

    public void setDelete_status(Integer delete_status) {
        this.delete_status = delete_status;
    }

}
