package com.threeti.danone.common.bean;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "spitting_up".
 */
public class SpittingUp extends Diary  {

    /** Not-null value. */
    private String appId;
    private String serverId;
    private String modifyReason;
    private String deleteReason;
    private String infantId;
    /** Not-null value. */
    private java.util.Date ddat;
    private Integer status;
    private String reguNumber;
    private String vomiNumber;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SpittingUp() {
    }

    public SpittingUp(String appId) {
        this.appId = appId;
    }

    public SpittingUp(String appId, String serverId, String modifyReason, String deleteReason, String infantId, java.util.Date ddat, Integer status, String reguNumber, String vomiNumber) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.ddat = ddat;
        this.status = status;
        this.reguNumber = reguNumber;
        this.vomiNumber = vomiNumber;
    }

    /** Not-null value. */
    public String getAppId() {
        return appId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getServerId() {
        return serverId;
    }

    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    public String getModifyReason() {
        return modifyReason;
    }

    public void setModifyReason(String modifyReason) {
        this.modifyReason = modifyReason;
    }

    public String getDeleteReason() {
        return deleteReason;
    }

    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason;
    }

    public String getInfantId() {
        return infantId;
    }

    public void setInfantId(String infantId) {
        this.infantId = infantId;
    }

    /** Not-null value. */
    public java.util.Date getDdat() {
        return ddat;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDdat(java.util.Date ddat) {
        this.ddat = ddat;
    }

    public String getReguNumber() {
        return reguNumber;
    }

    public void setReguNumber(String reguNumber) {
        this.reguNumber = reguNumber;
    }

    public String getVomiNumber() {
        return vomiNumber;
    }

    public void setVomiNumber(String vomiNumber) {
        this.vomiNumber = vomiNumber;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
