package com.threeti.danone.common.bean;

import com.threeti.danone.common.model.Diary;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "stool".
 */
public class Stool  extends Diary{


    private String stoolyn;
    private Integer type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Stool() {
    }

    public Stool(String appId, String serverId, String modifyReason, String deleteReason, String infantId, java.util.Date ddat, Integer status, String stoolyn, Integer type) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.ddat = ddat;
        this.status = status;
        this.stoolyn = stoolyn;
        this.type = type;
    }

   
    public String getStoolyn() {
        return stoolyn;
    }

    public void setStoolyn(String stoolyn) {
        this.stoolyn = stoolyn;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
