package com.threeti.danone.common.bean;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "stool".
 */
public class Stool  extends Diary {

	//N: no stool,Y: yes stool
    private String stoolyn;
    
    private String image;
    
    //1: Watery, 2: Soft, 3: Formed  4: Hard
    private Integer type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Stool() {
    }


    public Stool(String appId, String serverId, String modifyReason, String deleteReason, String infantId, java.util.Date ddat, Integer status, String stoolyn, String image, Integer type) {
        this.appId = appId;
        this.serverId = serverId;
        this.modifyReason = modifyReason;
        this.deleteReason = deleteReason;
        this.infantId = infantId;
        this.ddat = ddat;
        this.status = status;
        this.stoolyn = stoolyn;
        this.image = image;
        this.type = type;
    }

    public String getStoolyn() {
        return stoolyn;
    }

    public void setStoolyn(String stoolyn) {
        this.stoolyn = stoolyn;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
