package com.threeti.danone.common.bean;

import java.lang.String;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "student".
 */
public class Student extends BaseStudent  {

    private Long id;
    /** Not-null value. */
    private String name;
    private int age;
    private double score;
    /** Not-null value. */
    private String fancy;
    private String time;

    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    public Student(Long id, String name, int age, double score, String fancy, String time) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.score = score;
        this.fancy = fancy;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    /** Not-null value. */
    public String getFancy() {
        return fancy;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFancy(String fancy) {
        this.fancy = fancy;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
